apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands-frontend
  labels:
    app: openhands
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
      component: frontend
  template:
    metadata:
      labels:
        app: openhands
        component: frontend
    spec:
      containers:
      - name: frontend
        image: docker.all-hands.dev/all-hands-ai/openhands:0.23
        command: ["npm", "run", "dev", "--", "--port", "3001", "--host", "0.0.0.0"]
        workingDir: /app/frontend
        ports:
        - containerPort: 3001
        env:
        - name: VITE_BACKEND_HOST
          value: "openhands-backend-service:3000"
        - name: VITE_FRONTEND_PORT
          value: "3001"
        - name: HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: openhands-frontend-service
  labels:
    app: openhands
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: openhands
    component: frontend