apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-state-pvc
  namespace: openhands
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adjust based on your cluster's available storage classes