apiVersion: v1
kind: Service
metadata:
  name: openhands
  namespace: openhands
spec:
  selector:
    app: openhands
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: NodePort  # Using NodePort to expose the service externally
